### ISSUE TITLE
なにを作るのか決める

### ISSUE THREAD

**Issue by Kasiwamotchi** [Kasiwamotchi/landam_image#1]
## 背景とやること

これから作るアプリの概要を決める

## 実現方式とその根拠

* [x] どのようなアプリを作りたいか決める
* [x] 必要なものを決める
* [ ] 作業内容の素案を作る

## 完了条件

* [x] なにをしたいか決める
* [ ] 必要な素材を集める
* [x] 画面がどのような動きをするか書きだす
* [ ] 実装までの作業を書き出す

## やらないこと

コードを書く

**Comment by Kasiwamotchi** [comment]
## なにをしたいか
原名を見せて薔薇か百合かをあてることで花に癒されるアプリ作る
## 必要な素材
薔薇と百合に関するもの
写真・学名・和名・tips(花言葉とか？)
## 画面がどのような動きをするかのイメージ
Nextボタンで問題に入る
画面に学名が出る
百合か薔薇かボタンを押す
写真と和名とTipsが出る
Nextボタンで次の問題へ移る

**Comment by Kasiwamotchi** [comment]
## 必要そうなコンポーネントの洗い出し
百合ボタン　Ladixui
薔薇ボタン　Ladixui
次ボタン　Ladixui
画面コンポ―ネント

画面コンポーネントで扱う要素
最初の画面　（タイトルとか？）
学名
和名とかのTips

**Comment by Kasiwamotchi** [comment]
## 使いそうな関数
百合ボタン　クリックした情報を届ける
薔薇ボタン　クリックした情報を届ける
次ボタン　クリックした情報を届ける
画面コンポ―ネント　
以下の画面を表示する関数
最初の画面　（タイトルとか？）
学名
和名とかのTips

## 画面とユーザーの動きを書き出す
初期画面が表示される
次ボタンを押す
学名画面が表示される
百合ボタンか文字ボタンを押す
Tips画面が表示される
次ボタンを押す

## 処理を書き出してみる
初期画面が表示される
↓
次ボタンを押す
↓
↓次ボタンがオンクリックを起動する
↓
↓配列から学名を取得する
↓
↓取得した学名を表示する
↓
R.学名画面が表示される
↓
百合ボタンか文字ボタンを押す
↓
↓ボタンがオンクリックを起動する
↓
↓学名と同じオブジェクトに格納されているTipsを取得する
↓
↓取得したTipsを表示する
↓
Tips画面が表示される
↓
次ボタンを押す
↓
↓次ボタンがオンクリックを起動する
↓
↓配列から学名を取得する
↓
↓取得した学名を表示する
↓
以下Rからと同じ処理

**Comment by Kasiwamotchi** [comment]
## メモ
学名ではなく原名の方が良さそう
100問作りたいが手間と達成感と他の部分のクオリティとに釣り合わないので20問くらいにする
最低限の情報で花に萌えるのが目的なので○×とかしない

**Comment by konyaru** [comment]
@Kasiwamotchi 
何を作るのか決めるのもそうなんだけど、まずは下記のドキュメントの2番から進めるんだよ？
参照: https://qiita.com/Sicut_study/items/78910cd8d103b8d45a73

だから、「 [画像ランダム表示サイト](https://qiita.com/Sicut_study/items/78910cd8d103b8d45a73) 」を作るんだよ？
そのあと、3番のTODOアプリを作るんだからね

**Comment by konyaru** [comment]
あと、とりあえず困ったらLayoutから作りなね
 **手を動かすまでの時間を速くする** のが楽しく最速で開発するためのコツだから！

**Comment by Kasiwamotchi** [comment]
@konyaru 
確認しました
手順をまもりつつ一つ目の作業に入ります
